# bootstrap/main.tf
# Run this ONCE to create:
#   1. S3 bucket for Terraform state
#   2. DynamoDB table for state locking
#   3. OIDC provider + IAM role for GitHub Actions
#
# Usage:
#   cd bootstrap
#   terraform init
#   terraform apply

terraform {
  required_version = ">= 1.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
}

variable "aws_region" {
  default = "us-east-1"
}

variable "aws_profile" {
  default = null
}

variable "project_name" {
  default = "unleash-assessment"
}

variable "github_org" {
  description = "GitHub organization or username"
  type        = string
}

variable "github_repo" {
  description = "GitHub repository name"
  type        = string
}

locals {
  bucket_name = "${var.project_name}-tfstate-${data.aws_caller_identity.current.account_id}"
}

data "aws_caller_identity" "current" {}

#────────────────────────────────────────────────────────────────
# S3 BUCKET FOR TERRAFORM STATE
#────────────────────────────────────────────────────────────────
resource "aws_s3_bucket" "tfstate" {
  bucket = local.bucket_name

  lifecycle {
    prevent_destroy = true
  }

  tags = {
    Name    = "Terraform State"
    Project = var.project_name
  }
}

resource "aws_s3_bucket_versioning" "tfstate" {
  bucket = aws_s3_bucket.tfstate.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "tfstate" {
  bucket = aws_s3_bucket.tfstate.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "aws:kms"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "tfstate" {
  bucket                  = aws_s3_bucket.tfstate.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}


#────────────────────────────────────────────────────────────────
# IAM POLICY (generated by Pike - minimum permissions)
#────────────────────────────────────────────────────────────────
resource "aws_iam_policy" "github_actions" {
  name        = "${var.project_name}-github-actions-policy"
  description = "Minimum permissions for Terraform deployments (generated by Pike)"
  policy      = file("${path.module}/github_actions_policy.json")

  tags = {
    Project = var.project_name
  }
}

#────────────────────────────────────────────────────────────────
# GITHUB OIDC (using unfunco/oidc-github/aws module)
#────────────────────────────────────────────────────────────────
module "oidc_github" {
  source  = "unfunco/oidc-github/aws"
  version = "1.8.0"

  # OIDC provider already exists in account - skip creation
  create_oidc_provider = false

  # SECURITY: Restrict to main branch and protected environments only
  # NO pull_request access - PRs only run CI checks without AWS credentials
  github_repositories = [
    "${var.github_org}/${var.github_repo}:ref:refs/heads/main",
    "${var.github_org}/${var.github_repo}:environment:global",
    "${var.github_org}/${var.github_repo}:environment:us-east-1",
    "${var.github_org}/${var.github_repo}:environment:eu-west-1"
  ]

  iam_role_name        = "${var.project_name}-github-actions"
  iam_role_policy_arns = [aws_iam_policy.github_actions.arn]

  tags = {
    Project = var.project_name
  }
}

#────────────────────────────────────────────────────────────────
# OUTPUTS
#────────────────────────────────────────────────────────────────
output "s3_bucket" {
  value       = aws_s3_bucket.tfstate.bucket
  description = "S3 bucket for Terraform state"
}

output "github_actions_role_arn" {
  value       = module.oidc_github.iam_role_arn
  description = "IAM role ARN for GitHub Actions - add to GitHub Secrets as AWS_ROLE_ARN"
}

output "backend_config" {
  value       = <<-EOT
    # Copy this to environments/dev/backend.tf
    terraform {
      backend "s3" {
        bucket       = "${aws_s3_bucket.tfstate.bucket}"
        key          = "dev/terraform.tfstate"
        region       = "${var.aws_region}"
        encrypt      = true
        use_lockfile = true  # Native S3 locking (Terraform 1.10+)
      }
    }
  EOT
  description = "Backend configuration to copy"
}
